# Generated by Django 3.2.5 on 2021-07-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nov', models.CharField(max_length=25, null=True)),
                ('docket_no', models.CharField(max_length=25, null=True)),
                ('nov_issued_date', models.DateField(null=True)),
                ('hearing_date', models.DateField(null=True)),
                ('street_dir', models.CharField(max_length=5, null=True)),
                ('street_name', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('violation', models.CharField(max_length=250, null=True)),
                ('disposition', models.CharField(max_length=250, null=True)),
                ('admin_cost', models.IntegerField(null=True)),
                ('sanction_cost', models.IntegerField(null=True)),
                ('fine', models.IntegerField(null=True)),
                ('respondent', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=200, unique=True)),
                ('numeric_address', models.IntegerField()),
                ('street_dir', models.CharField(max_length=1, null=True)),
                ('street_name', models.CharField(max_length=50)),
                ('street_suffix', models.CharField(max_length=10, null=True)),
                ('unit', models.CharField(max_length=30, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('metered', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=100)),
                ('numeric_address', models.IntegerField(null=True)),
                ('street_dir', models.CharField(max_length=1, null=True)),
                ('street_name', models.CharField(max_length=50)),
                ('street_suffix', models.CharField(max_length=10, null=True)),
                ('unit', models.CharField(max_length=30, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('bad_debt_no', models.CharField(max_length=50, null=True)),
                ('debt_collector', models.CharField(max_length=100)),
                ('debt_date', models.DateField(null=True)),
                ('debt_amt', models.IntegerField(null=True)),
                ('penalty', models.IntegerField(null=True)),
                ('payment', models.IntegerField(null=True)),
                ('payment_date', models.DateField(null=True)),
                ('payment_water', models.IntegerField(null=True)),
                ('payment_sewer', models.IntegerField(null=True)),
                ('payment_other', models.IntegerField(null=True)),
                ('payment_water_tax', models.IntegerField(null=True)),
                ('payment_sewer_tax', models.IntegerField(null=True)),
                ('payment_refuse', models.IntegerField(null=True)),
                ('payment_water_penalty', models.IntegerField(null=True)),
                ('payment_sewer_penalty', models.IntegerField(null=True)),
                ('payment_refuse_penalty', models.IntegerField(null=True)),
                ('fee_water', models.IntegerField(null=True)),
                ('fee_sewer', models.IntegerField(null=True)),
                ('fee_other', models.IntegerField(null=True)),
                ('fee_water_tax', models.IntegerField(null=True)),
                ('fee_sewer_tax', models.IntegerField(null=True)),
                ('fee_refuse', models.IntegerField(null=True)),
                ('fee_water_penalty', models.IntegerField(null=True)),
                ('fee_sewer_penalty', models.IntegerField(null=True)),
                ('fee_refuse_penalty', models.IntegerField(null=True)),
                ('prop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debt.property')),
            ],
        ),
    ]
