# Generated by Django 3.2.5 on 2021-07-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
    ]
