# Generated by Django 3.2.5 on 2021-07-22 21:45

from django.db import migrations
from debt.models import Property, Debt


def match(apps,schema_editor):
    for debt in Debt.objects.all():
        prop = debt.get_prop()
        if prop:
            debt.prop = prop
            debt.save()
            print('matching', debt.__dict__, prop.__dict__)




class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0002_load_props_debts_cases')
    ]

    operations = [
    migrations.RunPython(match)
    ]
