# Generated by Django 3.2.5 on 2021-09-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0003_match_props_to_debts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=5, null=True)),
                ('status', models.CharField(max_length=1, null=True)),
                ('metered', models.BooleanField(null=True)),
                ('balance', models.FloatField(null=True)),
                ('water_balance', models.FloatField(null=True)),
                ('sewer_balance', models.FloatField(null=True)),
                ('tax_balance', models.FloatField(null=True)),
                ('penalty_balance', models.FloatField(null=True)),
                ('garbage_balance', models.FloatField(null=True)),
                ('other_balance', models.FloatField(null=True)),
                ('no_delinquencies', models.FloatField(null=True)),
            ],
        ),
    ]
