# Generated by Django 3.2.5 on 2021-09-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0005_load_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_digit', models.CharField(max_length=5)),
                ('total_pop', models.IntegerField(null=True)),
                ('majority_race', models.CharField(max_length=20,null=True)),
            ],
        ),
    ]
