# Generated by Django 3.2.5 on 2021-09-29 21:03

from django.db import migrations
import agate, agateexcel
from debt.models import ZipCode
from water.settings import BASE_DIR

### START CONFIG ###
data_dir = str(BASE_DIR) + '/data/'
zip_data_path = data_dir + 'zip_race.xlsx'
### END CONFIG ###

def load_data(apps, schema_migration):
    zipcode_data = agate.Table.from_xlsx(zip_data_path,sheet='UI_Claims_By_ZIP_Code_Per_Capit')
    for zipcode in zipcode_data:
        try:
            zipcode = ZipCode.objects.create(
                five_digit = zipcode['ZIP Text'],
                total_pop = zipcode['Total Pop'],
                majority_race = zipcode['Majority']
                )
        except Exception as e:
            print(e)
            import ipdb; ipdb.set_trace()
        print(zipcode)
        zipcode.save()

class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0006_zipcode'),
    ]

    operations = [
            migrations.RunPython(load_data)
    ]
