# Generated by Django 3.2.5 on 2021-10-16 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0007_load_zips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_no', models.CharField(max_length=10, null=True)),
                ('violation_no', models.CharField(max_length=197, null=True)),
                ('issue_date', models.DateField()),
                ('issue_dept', models.CharField(max_length=7, null=True)),
                ('last_hearing_date', models.CharField(max_length=20, null=True)),
                ('property_address', models.CharField(max_length=22, null=True)),
                ('numeric_address', models.IntegerField(null=True)),
                ('street_dir', models.CharField(max_length=1, null=True)),
                ('street_name', models.CharField(max_length=50)),
                ('street_suffix', models.CharField(max_length=10, null=True)),
                ('unit', models.CharField(max_length=30, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('violation_type', models.CharField(max_length=20, null=True)),
                ('entity_person', models.CharField(max_length=105, null=True)),
                ('disposition', models.CharField(max_length=100, null=True)),
                ('fines', models.FloatField(null=True)),
                ('admin_costs', models.FloatField(null=True)),
                ('interest', models.FloatField(null=True)),
                ('collection_atty_fees', models.FloatField(null=True)),
                ('court_cost', models.FloatField(null=True)),
                ('original_total_due', models.FloatField(null=True)),
                ('total_paid', models.FloatField(null=True)),
                ('current_due', models.FloatField(null=True)),
                ('prop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debt.property')),
            ],
        ),
    ]
