# Generated by Django 3.2.5 on 2021-10-14 20:19
from django.db import migrations
from debt.models import Vacancy
from water.settings import BASE_DIR
import csv
from utils.migration_utils import partition_vacancy_address
from tcr_tools.typify import parse_str_date


### START CONFIG ###
data_dir = str(BASE_DIR) + '/data/'
vac_data_path = data_dir + 'vacancies.csv'
### END CONFIG ###

def load_vacancies(apps,schema_editor):
    for vac in csv.DictReader(open(vac_data_path)):
        part_add = partition_vacancy_address(vac['Property Address'])
        vacancy = Vacancy.objects.create(
            docket_no = vac['Docket Number'],
            violation_no = vac['Violation Number'],
            issue_date = parse_str_date(vac['Issued Date']),
            issue_dept = vac['Issuing Department'],
            last_hearing_date = parse_str_date(vac['Last Hearing Date']),
            property_address = vac['Property Address'],
            # address parts
            numeric_address = part_add['numerical'],
            street_dir = part_add['directional'],
            street_name = part_add['street_name'],
            street_suffix = part_add['street_suffix'],
            unit = part_add['unit'],
            zipcode = part_add['zipcode'],
            # end address parts
            violation_type = vac['Violation Type'],
            entity_person = vac['Entity or Person(s)'],
            disposition = vac['Disposition Description'],
            fines = vac['Total Fines'],
            admin_costs =  vac['Total Administrative Costs'],
            interest = vac['Interest Amount'],
            collection_atty_fees = vac['Collection Costs or Attorney Fees'],
            court_cost = vac['Court Cost'],
            original_total_due = vac['Original Total Amount Due'],
            total_paid = vac['Total Paid'],
            current_due = vac['Current Amount Due'],
            )
        vacancy.save()

class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0008_vacancy'),
    ]

    operations = [
            migrations.RunPython(load_vacancies)
    ]
