# Generated by Django 3.2.5 on 2021-10-15 00:27

from django.db import migrations
from debt.models import Property, Vacancy

def match(apps, schema_editor):
    for vacancy in Vacancy.objects.all():
        prop = vacancy.get_prop()
        if prop:
            vacancy.prop = prop
            vacancy.save()
            print('matching', vacancy.__dict__, prop.__dict__)



class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0009_load_vacancies'),
    ]

    operations = [
            migrations.RunPython(match)
    ]
