# Generated by Django 3.2.5 on 2021-11-01 21:33
from debt.models import Property
from django.db import migrations

def trim_zips(apps,schema_editor):
    for prop in Property.objects.all():
        if prop.zipcode:
            prop.zipcode = prop.zipcode[0:5]
            prop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0010_match_props_to_vacancies'),
    ]

    operations = [
            migrations.RunPython(trim_zips)
    ]
